# Generated by Django 5.0.2 on 2024-02-14 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_alter_orderitem_product_alter_product_collection_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reviw",
            new_name="Review",
        ),
    ]
