# Generated by Django 5.0.2 on 2024-03-26 18:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0011_alter_customer_options_remove_customer_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"permissions": [("cancel_order", "Can cancel order")]},
        ),
    ]
